### ISSUE TITLE
Add support for 'Twilight Forest'

### ISSUE THREAD

**Issue by stantios** [Kneelawk/extra-mod-integrations#1]

**Comment by Kneelawk** [comment]
I'm actually not very familiar with the Twilight Forest. If you could provide a list of machines/recipe types to add support for, that would be much appreciated :)

**Comment by Aquaeyes** [comment]
Unless I'm incorrect, it's present in EMI natively? At least, the transformation powder recipe type is.

**Comment by Kneelawk** [comment]
Oops, yup. Noticed that Twilight Forest recently added native EMI support when I was looking into this. Forgot to close this issue.
