### ISSUE TITLE
[Support Request] Artis-Recrafted

### ISSUE THREAD

**Issue by Nataly171** [Kneelawk/extra-mod-integrations#10]
[Artis-Recrafted](https://modrinth.com/mod/artisrecrafted) allows for registering custom tables and recipe types, unfortunately it doesn't currently have native EMI support.

**Comment by Abbie5** [comment]
Artis-Recrafted added native EMI support in version 4.0.0 https://modrinth.com/mod/artisrecrafted/version/4.0.0+1.20
