### ISSUE TITLE
[Support Request] AE2

### ISSUE THREAD

**Issue by Merith-TK** [Kneelawk/extra-mod-integrations#12]
![image](https://github.com/Kneelawk/extra-mod-integrations/assets/10422110/505ab9fc-9ed8-42ca-b75c-3bdedcc786ac)
This is what happens for charged certus quartz crystals

**Comment by Kneelawk** [comment]
Yeah, I need to get working on incorporating EMICompat. That will also include fixing it up.

**Comment by Kneelawk** [comment]
Related to #11

**Comment by jthvai** [comment]
AE2 now has native EMI support for 1.20.4+ (though that version hasn't landed for fabric yet)
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7509

**Comment by Kneelawk** [comment]
1.20.4+ AE2 won't be coming to fabric :(

However, ExMI supports *most* of AE2 now. So I'll probably close this issue.

**Comment by jthvai** [comment]
> 1.20.4+ AE2 won't be coming to fabric :(

D: Where did you see this?

Edit: I've now found several messages in the AE2 discord from their devs confirming this (but haven't found any official communication).
