### ISSUE TITLE
Support for Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by Jamesssssssssssssss** [Kneelawk/extra-mod-integrations#31]
The original [Farmer's Delight fabric port by Zifiv](https://modrinth.com/mod/farmers-delight-fabric) has been deprecated. The recommended version is now [Farmer's Delight refabricated](https://modrinth.com/mod/farmers-delight-refabricated). 

Currently extra mod integrations says 

`[Extra Mod Integrations] Skipping integration for Farmer's Delight (mod not found)` 

when using the refabricated version. Please consider supporting this version! Thank you

**Comment by unilock** [comment]
Farmer's Delight Refabricated has EMI support built-in already.

https://github.com/MehVahdJukaar/FarmersDelight/tree/1.20/src/main/java/vectorwing/farmersdelight/integration/emi

**Comment by Kneelawk** [comment]
Oop, this issue should have been closed when we fixed the incompatibility with Refabricated.
