### ISSUE TITLE
1.18.2 Backport?

### ISSUE THREAD

**Issue by ConqAra** [Kneelawk/extra-mod-integrations#4]
Is it possible for you to try and make a 1.18.2 backport? Really love tech reborn and EMI but the modpack i have is on 1.18.2

**Comment by Kneelawk** [comment]
The mod is actually on its way to releasing a 1.18.2 version, thanks to JoostMSoftware. I just need to patch up a couple things and I should be able to make a release.

**Comment by KirboSoftware** [comment]
Yea I'm working on it, don't you worry!

**Comment by Kneelawk** [comment]
Ok, a 1.18.2 backport `v0.0.1+1.18.2` has been released on [Modrinth](https://modrinth.com/mod/extra-mod-integrations/version/0.0.1+1.18.2) & [Curseforge](https://www.curseforge.com/minecraft/mc-mods/emi-addon-extra-mod-integrations/files/4277367).
