### ISSUE TITLE
Crash when rendering certain Tech Reborn screens with EMI 0.5.x

### ISSUE THREAD

**Issue by CookieGD** [Kneelawk/extra-mod-integrations#6]
[crash-2022-12-28_23.15.45-client.txt](https://github.com/Kneelawk/extra-mod-integrations/files/10316825/crash-2022-12-28_23.15.45-client.txt)
[crash-2022-12-28_23.29.04-client.txt](https://github.com/Kneelawk/extra-mod-integrations/files/10316826/crash-2022-12-28_23.29.04-client.txt)
[crash-2022-12-28_23.51.43-client.txt](https://github.com/Kneelawk/extra-mod-integrations/files/10316827/crash-2022-12-28_23.51.43-client.txt)

These are all EMI-related crashes I got in the past hour.

**Comment by Kneelawk** [comment]
Ok, a fix for this `0.1.1+1.19.2` has been released on [Modrinth](https://modrinth.com/mod/extra-mod-integrations/version/0.1.1+1.19.2) & [Curseforge](https://www.curseforge.com/minecraft/mc-mods/emi-addon-extra-mod-integrations/files/4277377).
